CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    username VARCHAR(127) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    password_hash BYTEA NOT NULL DEFAULT '\x00'
);