# docker services for development

x-postgres: &postgres
  image: postgres:18-alpine
  ports:
    - "5432:5432"
  environment:
    POSTGRES_DB: db
    POSTGRES_PASSWORD: db
    POSTGRES_USER: db
  healthcheck:
    test: [ "CMD-SHELL", "pg_isready -U db -d db" ]
    interval: 1s
    timeout: 5s
    retries: 20

services:
  postgres:
    <<: *postgres
    volumes:
      - pgdata:/var/lib/postgresql

  postgres_test:
    <<: *postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql

  mailpit:
    image: axllent/mailpit
    restart: unless-stopped
    volumes:
      - mails:/data
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  pgdata:
  pgdata_test:
  mails:
