# docker services for development

x-postgres: &postgres
  image: postgres:18-alpine
  ports:
    - "5432:5432"
  environment:
    POSTGRES_DB: db
    POSTGRES_PASSWORD: db
    POSTGRES_USER: db
  healthcheck:
    test: [ "CMD-SHELL", "pg_isready -U db -d db" ]
    interval: 1s
    timeout: 5s
    retries: 20

services:
  postgres:
    <<: *postgres
    volumes:
      - pgdata:/var/lib/postgresql

  postgres_test:
    <<: *postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql

volumes:
  pgdata:
  pgdata_test:
