// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coin.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLockedBalance = `-- name: GetLockedBalance :one
SELECT balance FROM coin_balances WHERE player_id = $1 FOR UPDATE
`

func (q *Queries) GetLockedBalance(ctx context.Context, playerID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getLockedBalance, playerID)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const getPlayerBalance = `-- name: GetPlayerBalance :one
SELECT cb.balance FROM coin_balances cb
JOIN minecraft_players mp ON mp.id = cb.player_id WHERE mp.uuid = $1
`

func (q *Queries) GetPlayerBalance(ctx context.Context, uuid string) (int64, error) {
	row := q.db.QueryRow(ctx, getPlayerBalance, uuid)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const insertCoinTransaction = `-- name: InsertCoinTransaction :exec
INSERT INTO coin_transactions (player_id, amount, source, description, actor_user_id, actor_token_id)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertCoinTransactionParams struct {
	PlayerID     int64
	Amount       int64
	Source       CoinSource
	Description  pgtype.Text
	ActorUserID  pgtype.Int8
	ActorTokenID pgtype.Int8
}

func (q *Queries) InsertCoinTransaction(ctx context.Context, arg InsertCoinTransactionParams) error {
	_, err := q.db.Exec(ctx, insertCoinTransaction,
		arg.PlayerID,
		arg.Amount,
		arg.Source,
		arg.Description,
		arg.ActorUserID,
		arg.ActorTokenID,
	)
	return err
}

const listPlayerTransactions = `-- name: ListPlayerTransactions :many
SELECT id, player_id, amount, source, description, created_at, actor_user_id, actor_token_id
FROM coin_transactions WHERE player_id = $1
ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListPlayerTransactionsParams struct {
	PlayerID int64
	Limit    int32
	Offset   int32
}

func (q *Queries) ListPlayerTransactions(ctx context.Context, arg ListPlayerTransactionsParams) ([]CoinTransaction, error) {
	rows, err := q.db.Query(ctx, listPlayerTransactions, arg.PlayerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoinTransaction
	for rows.Next() {
		var i CoinTransaction
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.Amount,
			&i.Source,
			&i.Description,
			&i.CreatedAt,
			&i.ActorUserID,
			&i.ActorTokenID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBalance = `-- name: UpsertBalance :one
INSERT INTO coin_balances (player_id, balance, updated_at) VALUES ($1, $2, now())
ON CONFLICT (player_id) DO UPDATE
  SET balance = coin_balances.balance + $2, updated_at = now()
RETURNING balance
`

type UpsertBalanceParams struct {
	PlayerID int64
	Balance  int64
}

func (q *Queries) UpsertBalance(ctx context.Context, arg UpsertBalanceParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertBalance, arg.PlayerID, arg.Balance)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}
