// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invitation.sql

package sqlc

import (
	"context"
)

const getValidInvitation = `-- name: GetValidInvitation :one
SELECT id, user_id FROM user_invitations
WHERE token = $1 AND expires_at > now() AND used_at IS NULL
`

type GetValidInvitationRow struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetValidInvitation(ctx context.Context, token string) (GetValidInvitationRow, error) {
	row := q.db.QueryRow(ctx, getValidInvitation, token)
	var i GetValidInvitationRow
	err := row.Scan(&i.ID, &i.UserID)
	return i, err
}

const insertInvitation = `-- name: InsertInvitation :exec
INSERT INTO user_invitations (user_id, token, expires_at)
VALUES ($1, $2, now() + interval '24 hours')
`

type InsertInvitationParams struct {
	UserID int64
	Token  string
}

func (q *Queries) InsertInvitation(ctx context.Context, arg InsertInvitationParams) error {
	_, err := q.db.Exec(ctx, insertInvitation, arg.UserID, arg.Token)
	return err
}

const markInvitationUsed = `-- name: MarkInvitationUsed :exec
UPDATE user_invitations SET used_at = now() WHERE id = $1
`

func (q *Queries) MarkInvitationUsed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markInvitationUsed, id)
	return err
}

const verifyUser = `-- name: VerifyUser :exec
UPDATE users SET password_hash = $1, verified_at = now() WHERE id = $2
`

type VerifyUserParams struct {
	PasswordHash []byte
	ID           int64
}

func (q *Queries) VerifyUser(ctx context.Context, arg VerifyUserParams) error {
	_, err := q.db.Exec(ctx, verifyUser, arg.PasswordHash, arg.ID)
	return err
}
