// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CoinSource string

const (
	CoinSourceMinigame CoinSource = "minigame"
	CoinSourceAdmin    CoinSource = "admin"
	CoinSourcePurchase CoinSource = "purchase"
	CoinSourceSystem   CoinSource = "system"
)

func (e *CoinSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CoinSource(s)
	case string:
		*e = CoinSource(s)
	default:
		return fmt.Errorf("unsupported scan type for CoinSource: %T", src)
	}
	return nil
}

type NullCoinSource struct {
	CoinSource CoinSource
	Valid      bool // Valid is true if CoinSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCoinSource) Scan(value interface{}) error {
	if value == nil {
		ns.CoinSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CoinSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCoinSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CoinSource), nil
}

type AccessToken struct {
	ID        int64
	UserID    int64
	Name      string
	CreatedAt pgtype.Timestamp
	ExpiresAt pgtype.Timestamp
	Revoked   pgtype.Bool
	Scopes    []byte
}

type CoinBalance struct {
	PlayerID  int64
	Balance   int64
	UpdatedAt pgtype.Timestamp
}

type CoinTransaction struct {
	ID           int64
	PlayerID     int64
	Amount       int64
	Source       CoinSource
	Description  pgtype.Text
	CreatedAt    pgtype.Timestamp
	ActorUserID  pgtype.Int8
	ActorTokenID pgtype.Int8
}

type MinecraftPlayer struct {
	ID                int64
	Uuid              string
	CreatedAt         pgtype.Timestamp
	Username          pgtype.Text
	UsernameFetchedAt pgtype.Timestamp
	Data              []byte
}

type Role struct {
	ID        int64
	Name      string
	CreatedAt pgtype.Timestamp
	Protected bool
}

type Session struct {
	ID        int64
	UserID    int64
	CreatedAt pgtype.Timestamp
	ExpiresAt pgtype.Timestamp
}

type User struct {
	ID           int64
	Username     string
	Email        string
	CreatedAt    pgtype.Timestamp
	PasswordHash []byte
	VerifiedAt   pgtype.Timestamp
}

type UserInvitation struct {
	ID        int64
	UserID    int64
	Token     string
	CreatedAt pgtype.Timestamp
	ExpiresAt pgtype.Timestamp
	UsedAt    pgtype.Timestamp
}
