// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const deletePlayerByUUID = `-- name: DeletePlayerByUUID :execresult
DELETE FROM minecraft_players WHERE uuid = $1
`

func (q *Queries) DeletePlayerByUUID(ctx context.Context, uuid string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deletePlayerByUUID, uuid)
}

const deletePlayerDataAtPath = `-- name: DeletePlayerDataAtPath :execresult
UPDATE minecraft_players SET data = data #- $1::text[] WHERE uuid = $2
`

type DeletePlayerDataAtPathParams struct {
	Column1 []string
	Uuid    string
}

func (q *Queries) DeletePlayerDataAtPath(ctx context.Context, arg DeletePlayerDataAtPathParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deletePlayerDataAtPath, arg.Column1, arg.Uuid)
}

const getPlayerByUUID = `-- name: GetPlayerByUUID :one
SELECT id, uuid, username, created_at, username_fetched_at FROM minecraft_players WHERE uuid = $1
`

type GetPlayerByUUIDRow struct {
	ID                int64
	Uuid              string
	Username          pgtype.Text
	CreatedAt         pgtype.Timestamp
	UsernameFetchedAt pgtype.Timestamp
}

func (q *Queries) GetPlayerByUUID(ctx context.Context, uuid string) (GetPlayerByUUIDRow, error) {
	row := q.db.QueryRow(ctx, getPlayerByUUID, uuid)
	var i GetPlayerByUUIDRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Username,
		&i.CreatedAt,
		&i.UsernameFetchedAt,
	)
	return i, err
}

const getPlayerData = `-- name: GetPlayerData :one
SELECT data FROM minecraft_players WHERE uuid = $1
`

func (q *Queries) GetPlayerData(ctx context.Context, uuid string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getPlayerData, uuid)
	var data []byte
	err := row.Scan(&data)
	return data, err
}

const getPlayerDataAtPath = `-- name: GetPlayerDataAtPath :one
SELECT data #> $1::text[] FROM minecraft_players WHERE uuid = $2
`

type GetPlayerDataAtPathParams struct {
	Column1 []string
	Uuid    string
}

func (q *Queries) GetPlayerDataAtPath(ctx context.Context, arg GetPlayerDataAtPathParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, getPlayerDataAtPath, arg.Column1, arg.Uuid)
	var column_1 interface{}
	err := row.Scan(&column_1)
	return column_1, err
}

const getPlayerDataForUpdate = `-- name: GetPlayerDataForUpdate :one
SELECT data FROM minecraft_players WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetPlayerDataForUpdate(ctx context.Context, id int64) ([]byte, error) {
	row := q.db.QueryRow(ctx, getPlayerDataForUpdate, id)
	var data []byte
	err := row.Scan(&data)
	return data, err
}

const getPlayerIDAndFetchTime = `-- name: GetPlayerIDAndFetchTime :one
SELECT id, username_fetched_at FROM minecraft_players WHERE uuid = $1
`

type GetPlayerIDAndFetchTimeRow struct {
	ID                int64
	UsernameFetchedAt pgtype.Timestamp
}

func (q *Queries) GetPlayerIDAndFetchTime(ctx context.Context, uuid string) (GetPlayerIDAndFetchTimeRow, error) {
	row := q.db.QueryRow(ctx, getPlayerIDAndFetchTime, uuid)
	var i GetPlayerIDAndFetchTimeRow
	err := row.Scan(&i.ID, &i.UsernameFetchedAt)
	return i, err
}

const getPlayerUUIDByName = `-- name: GetPlayerUUIDByName :one
SELECT uuid FROM minecraft_players
WHERE LOWER(username) = LOWER($1) AND username_fetched_at > now() - INTERVAL '1 hour'
`

func (q *Queries) GetPlayerUUIDByName(ctx context.Context, lower string) (string, error) {
	row := q.db.QueryRow(ctx, getPlayerUUIDByName, lower)
	var uuid string
	err := row.Scan(&uuid)
	return uuid, err
}

const insertPlayerByUUID = `-- name: InsertPlayerByUUID :one
INSERT INTO minecraft_players (uuid) VALUES ($1)
ON CONFLICT (uuid) DO NOTHING RETURNING id
`

func (q *Queries) InsertPlayerByUUID(ctx context.Context, uuid string) (int64, error) {
	row := q.db.QueryRow(ctx, insertPlayerByUUID, uuid)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listPlayers = `-- name: ListPlayers :many
SELECT id, uuid, username, created_at
FROM minecraft_players
WHERE ($1 = ''
       OR LOWER(username) LIKE '%' || LOWER($1) || '%'
       OR LOWER(uuid::text) = LOWER($1))
ORDER BY
  CASE WHEN $1 = '' THEN 0 ELSE 1 END,
  CASE WHEN LOWER(uuid::text) = LOWER($1) THEN 0 ELSE 1 END,
  similarity(username, $1) DESC,
  created_at DESC
LIMIT $2 OFFSET $3
`

type ListPlayersParams struct {
	Column1 interface{}
	Limit   int32
	Offset  int32
}

type ListPlayersRow struct {
	ID        int64
	Uuid      string
	Username  pgtype.Text
	CreatedAt pgtype.Timestamp
}

func (q *Queries) ListPlayers(ctx context.Context, arg ListPlayersParams) ([]ListPlayersRow, error) {
	rows, err := q.db.Query(ctx, listPlayers, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlayersRow
	for rows.Next() {
		var i ListPlayersRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Username,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlayerData = `-- name: UpdatePlayerData :exec
UPDATE minecraft_players SET data = $1::jsonb WHERE id = $2
`

type UpdatePlayerDataParams struct {
	Column1 []byte
	ID      int64
}

func (q *Queries) UpdatePlayerData(ctx context.Context, arg UpdatePlayerDataParams) error {
	_, err := q.db.Exec(ctx, updatePlayerData, arg.Column1, arg.ID)
	return err
}

const updatePlayerUsername = `-- name: UpdatePlayerUsername :exec
UPDATE minecraft_players SET username = NULLIF($1, ''), username_fetched_at = now() WHERE id = $2
`

type UpdatePlayerUsernameParams struct {
	Column1 interface{}
	ID      int64
}

func (q *Queries) UpdatePlayerUsername(ctx context.Context, arg UpdatePlayerUsernameParams) error {
	_, err := q.db.Exec(ctx, updatePlayerUsername, arg.Column1, arg.ID)
	return err
}

const upsertPlayerWithUsername = `-- name: UpsertPlayerWithUsername :exec
INSERT INTO minecraft_players (uuid, username, username_fetched_at)
VALUES ($1, $2, now())
ON CONFLICT (uuid) DO UPDATE SET username = EXCLUDED.username, username_fetched_at = now()
`

type UpsertPlayerWithUsernameParams struct {
	Uuid     string
	Username pgtype.Text
}

func (q *Queries) UpsertPlayerWithUsername(ctx context.Context, arg UpsertPlayerWithUsernameParams) error {
	_, err := q.db.Exec(ctx, upsertPlayerWithUsername, arg.Uuid, arg.Username)
	return err
}
