// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: role.sql

package sqlc

import (
	"context"
)

const createRole = `-- name: CreateRole :one
INSERT INTO roles (name) VALUES ($1) RETURNING id, name, created_at, protected
`

func (q *Queries) CreateRole(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRow(ctx, createRole, name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.Protected,
	)
	return i, err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles WHERE name = $1
`

func (q *Queries) DeleteRole(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteRole, name)
	return err
}

const getRoleProtected = `-- name: GetRoleProtected :one
SELECT protected FROM roles WHERE name = $1
`

func (q *Queries) GetRoleProtected(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRow(ctx, getRoleProtected, name)
	var protected bool
	err := row.Scan(&protected)
	return protected, err
}

const initRole = `-- name: InitRole :exec
INSERT INTO roles (name, protected) VALUES ($1, TRUE) ON CONFLICT DO NOTHING
`

func (q *Queries) InitRole(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, initRole, name)
	return err
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, created_at, protected FROM roles ORDER BY name
`

func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.Protected,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const roleExists = `-- name: RoleExists :one
SELECT EXISTS(SELECT 1 FROM roles WHERE name = $1)
`

func (q *Queries) RoleExists(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRow(ctx, roleExists, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
