// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const insertSession = `-- name: InsertSession :one
INSERT INTO sessions (user_id, expires_at) VALUES ($1, $2) RETURNING id
`

type InsertSessionParams struct {
	UserID    int64
	ExpiresAt pgtype.Timestamp
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertSession, arg.UserID, arg.ExpiresAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const refreshSession = `-- name: RefreshSession :execresult
UPDATE sessions SET expires_at = $1 WHERE id = $2 AND user_id = $3
`

type RefreshSessionParams struct {
	ExpiresAt pgtype.Timestamp
	ID        int64
	UserID    int64
}

func (q *Queries) RefreshSession(ctx context.Context, arg RefreshSessionParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, refreshSession, arg.ExpiresAt, arg.ID, arg.UserID)
}

const sessionExists = `-- name: SessionExists :one
SELECT EXISTS(
  SELECT 1 FROM sessions WHERE id = $1 AND user_id = $2 AND expires_at > now()
)
`

type SessionExistsParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) SessionExists(ctx context.Context, arg SessionExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, sessionExists, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
