// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: token.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const getTokenAuth = `-- name: GetTokenAuth :one
SELECT scopes, revoked FROM access_tokens
WHERE id = $1 AND user_id = $2 AND expires_at > now()
`

type GetTokenAuthParams struct {
	ID     int64
	UserID int64
}

type GetTokenAuthRow struct {
	Scopes  []byte
	Revoked pgtype.Bool
}

func (q *Queries) GetTokenAuth(ctx context.Context, arg GetTokenAuthParams) (GetTokenAuthRow, error) {
	row := q.db.QueryRow(ctx, getTokenAuth, arg.ID, arg.UserID)
	var i GetTokenAuthRow
	err := row.Scan(&i.Scopes, &i.Revoked)
	return i, err
}

const insertToken = `-- name: InsertToken :one
INSERT INTO access_tokens (user_id, name, expires_at, scopes)
VALUES ($1, $2, $3, $4) RETURNING id
`

type InsertTokenParams struct {
	UserID    int64
	Name      string
	ExpiresAt pgtype.Timestamp
	Scopes    []byte
}

func (q *Queries) InsertToken(ctx context.Context, arg InsertTokenParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertToken,
		arg.UserID,
		arg.Name,
		arg.ExpiresAt,
		arg.Scopes,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listTokens = `-- name: ListTokens :many
SELECT id, name, created_at, expires_at, revoked, scopes
FROM access_tokens WHERE user_id = $1 ORDER BY created_at DESC
`

type ListTokensRow struct {
	ID        int64
	Name      string
	CreatedAt pgtype.Timestamp
	ExpiresAt pgtype.Timestamp
	Revoked   pgtype.Bool
	Scopes    []byte
}

func (q *Queries) ListTokens(ctx context.Context, userID int64) ([]ListTokensRow, error) {
	rows, err := q.db.Query(ctx, listTokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTokensRow
	for rows.Next() {
		var i ListTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.Revoked,
			&i.Scopes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeToken = `-- name: RevokeToken :execresult
UPDATE access_tokens SET revoked = TRUE
WHERE id = $1 AND user_id = $2 AND revoked = FALSE
`

type RevokeTokenParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) RevokeToken(ctx context.Context, arg RevokeTokenParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, revokeToken, arg.ID, arg.UserID)
}
