// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc

import (
	"context"
)

const addUser = `-- name: AddUser :one
INSERT INTO users (username, email, password_hash, verified_at)
VALUES ($1, $2, $3, now())
RETURNING id
`

type AddUserParams struct {
	Username     string
	Email        string
	PasswordHash []byte
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, addUser, arg.Username, arg.Email, arg.PasswordHash)
	var id int64
	err := row.Scan(&id)
	return id, err
}
